# -*- coding: utf-8 -*-
"""webscraping-video4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qlg0mqjJVF5EdmkEupway2-nt_Dmug8g
"""

import requests
import re

url = "https://monicahillman.github.io/monibank/"
response = requests.get(url)
html_content = response.text

pattern = r'<(h[1|2])[^>]*>(.*?)<\/\1>'

headings = re.findall(pattern, html_content, re.DOTALL)
for heading in headings:
  print(heading)